# -*- coding: utf-8 -*-
"""Db11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LtCp-2nkIlp5NRSlZXRM_ssQ3nDnCFPn
"""

from google.colab import drive

# Check if Drive is already mounted
import os
if not os.path.exists('/content/drive'):
  drive.mount('/content/drive')
else:
  print("Drive is already mounted.")

import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, SimpleRNN, LSTM, GRU, Dense, Dropout
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_recall_fscore_support
from sklearn.preprocessing import LabelEncoder

# Step 1: Load the datasets
instagram_dataset = pd.read_csv('/content/drive/MyDrive/new/572-hate-speech-dataset.csv')
facebook_dataset = pd.read_csv('/content/drive/MyDrive/new/2020-12-31-DynamicallyGeneratedHateDataset-entries-v0.1.csv')
twitter_dataset = pd.read_csv('/content/drive/MyDrive/new/binary_cyberbullying.csv')

# Import necessary libraries
import pandas as pd

# Load datasets
instagram_dataset = pd.read_csv('/content/drive/MyDrive/new/572-hate-speech-dataset.csv')
facebook_dataset = pd.read_csv('/content/drive/MyDrive/new/2020-12-31-DynamicallyGeneratedHateDataset-entries-v0.1.csv')
twitter_dataset = pd.read_csv('/content/drive/MyDrive/new/binary_cyberbullying.csv')

# Preview the datasets
print(instagram_dataset.head())
print(facebook_dataset.head())
print(twitter_dataset.head())

# Standardizing labels across the datasets
# Instagram dataset: We will assume that "HS" is hate speech, and anything else is normal.
instagram_dataset['label'] = instagram_dataset['class'].apply(lambda x: 'hate' if x == 'HS' else 'normal')

# Facebook dataset: The label is already in "hate" and "non-hate". We'll map it to "hate" and "normal".
facebook_dataset['label'] = facebook_dataset['label'].apply(lambda x: 'hate' if x == 'hate' else 'normal')

# Twitter dataset: We assume "cyberbullying" is equivalent to "hate" and "Normal" is normal.
twitter_dataset['label'] = twitter_dataset['binary_class'].apply(lambda x: 'hate' if x != 'Normal' else 'normal')

# Select only the text and the labels for each dataset for consistency
instagram_cleaned = instagram_dataset[['comment_text', 'label']].rename(columns={'comment_text': 'text'})
facebook_cleaned = facebook_dataset[['text', 'label']]
twitter_cleaned = twitter_dataset[['tweet_text', 'label']].rename(columns={'tweet_text': 'text'})

# Combine the datasets
combined_dataset = pd.concat([instagram_cleaned, facebook_cleaned, twitter_cleaned], ignore_index=True)

# Show the distribution of the labels
print(combined_dataset['label'].value_counts())
print(combined_dataset.head())

# Check how many rows were dropped due to missing values
print("Before removing NaN values:", len(instagram_dataset) + len(facebook_dataset) + len(twitter_dataset))
print("After removing NaN values:", len(combined_dataset))

from sklearn.utils.class_weight import compute_class_weight
import numpy as np

# Compute class weights
class_weights = compute_class_weight("balanced", classes=np.unique(combined_dataset["label"]), y=combined_dataset["label"])
class_weights = {i: class_weights[i] for i in range(len(class_weights))}

# Train model with class weights
history = model.fit(X_train, y_train, epochs=10, batch_size=32,
                    validation_data=(X_test, y_test), class_weight=class_weights)

from sklearn.utils.class_weight import compute_class_weight
import numpy as np

# Compute class weights
class_weights = compute_class_weight("balanced", classes=np.unique(combined_dataset["label"]), y=combined_dataset["label"])
class_weights = {i: class_weights[i] for i in range(len(class_weights))}

# Train model with class weights
history = model.fit(X_train, y_train, epochs=10, batch_size=32,
                    validation_data=(X_test, y_test), class_weight=class_weights)

from imblearn.over_sampling import RandomOverSampler

# Convert labels to numerical values
label_mapping = {"hate": 0, "normal": 1}
combined_dataset["label"] = combined_dataset["label"].map(label_mapping)

# Apply oversampling to balance classes
oversampler = RandomOverSampler(sampling_strategy="auto", random_state=42)
X_resampled, y_resampled = oversampler.fit_resample(combined_dataset["text"].values.reshape(-1, 1), combined_dataset["label"])

# Convert back to DataFrame
balanced_dataset = pd.DataFrame({"text": X_resampled.flatten(), "label": y_resampled})

# Check new class distribution
print(balanced_dataset["label"].value_counts())

from imblearn.under_sampling import RandomUnderSampler

undersampler = RandomUnderSampler(sampling_strategy=1.0, random_state=42)
X_resampled, y_resampled = undersampler.fit_resample(combined_dataset["text"].values.reshape(-1, 1), combined_dataset["label"])

# Convert back to DataFrame
balanced_dataset = pd.DataFrame({"text": X_resampled.flatten(), "label": y_resampled})

# Check new class distribution
print(balanced_dataset["label"].value_counts())

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

# Define tokenizer
tokenizer = Tokenizer(num_words=10000, oov_token="<OOV>")
tokenizer.fit_on_texts(combined_dataset["text"])

# Convert text to sequences
sequences = tokenizer.texts_to_sequences(combined_dataset["text"])

# Pad sequences
padded_sequences = pad_sequences(sequences, maxlen=100, padding="post")

# Encode labels
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
labels = label_encoder.fit_transform(combined_dataset["label"])

# Train-test split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(padded_sequences, labels, test_size=0.2, random_state=42)

print("Final Training Set Shape:", X_train.shape, y_train.shape)
print("Final Testing Set Shape:", X_test.shape, y_test.shape)

# Check class distribution
print(combined_dataset["label"].value_counts())

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from sklearn.model_selection import train_test_split

# Define the maximum number of words to consider in the vocabulary and the maximum sequence length
vocab_size = 10000
max_length = 100

# Initialize the tokenizer
tokenizer = Tokenizer(num_words=vocab_size, oov_token="<OOV>")

# Fit the tokenizer on the dataset's text
tokenizer.fit_on_texts(combined_dataset["text"])

# Convert text to sequences
sequences = tokenizer.texts_to_sequences(combined_dataset["text"])

# Pad sequences to ensure uniform length
padded_sequences = pad_sequences(sequences, maxlen=max_length, padding="post", truncating="post")

# Encode labels (assuming labels are in the "label" column and are categorical)
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
labels = label_encoder.fit_transform(combined_dataset["label"])

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(padded_sequences, labels, test_size=0.2, random_state=42)

# Print dataset shapes for confirmation
print("Training set shape:", X_train.shape, y_train.shape)
print("Testing set shape:", X_test.shape, y_test.shape)

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, GRU, Dense, Dropout

# Define vocabulary size and sequence length
vocab_size = 10000  # Must match Tokenizer's num_words
embedding_dim = 128  # Size of word embedding vectors
max_length = 100  # Sequence length used for padding

# Define the model
model = Sequential([
    # Embedding layer
    Embedding(input_dim=vocab_size, output_dim=embedding_dim),

    # GRU layer
    GRU(128, return_sequences=False, dropout=0.2, recurrent_dropout=0.2),

    # Fully connected layers
    Dense(64, activation="relu"),
    Dropout(0.2),

    # Output layer for binary classification
    Dense(1, activation="sigmoid")
])

# Build the model explicitly
model.build(input_shape=(None, max_length))

# Compile the model
model.compile(optimizer="adam", loss="binary_crossentropy", metrics=["accuracy"])

# Display the model's architecture
model.summary()

# Define batch size and number of epochs
batch_size = 32
epochs = 10  # Adjust based on performance

# Train the model
history = model.fit(
    X_train, y_train,
    batch_size=batch_size,
    epochs=epochs,
    validation_data=(X_test, y_test),
    verbose=1
)

# Explicitly build the model
model.build(input_shape=(None, 100))
model.summary()

print("X_train Shape:", X_train.shape)
print("X_test Shape:", X_test.shape)

X_train = X_train.reshape(-1, 100)
X_test = X_test.reshape(-1, 100)

from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Embedding, GRU, Dense, Dropout, BatchNormalization

# Define input layer
inputs = Input(shape=(100,))

# Embedding layer
x = Embedding(input_dim=10000, output_dim=128)(inputs)

# GRU layers
x = GRU(128, return_sequences=True, dropout=0.2, recurrent_dropout=0.2)(x)
x = GRU(64, return_sequences=False, dropout=0.2, recurrent_dropout=0.2)(x)

# Batch Normalization + Fully Connected Layer
x = BatchNormalization()(x)
x = Dense(64, activation="relu")(x)
x = Dropout(0.3)(x)

# Output Layer
outputs = Dense(1, activation="sigmoid")(x)

# Create Model
model = Model(inputs, outputs)

# Compile Model
model.compile(optimizer="adam", loss="binary_crossentropy", metrics=["accuracy"])

# Show Model Summary
model.summary()

rnn_model = Sequential([
    Embedding(input_dim=10000, output_dim=128),
    SimpleRNN(128, return_sequences=False, dropout=0.2),
    Dense(64, activation="relu"),
    Dropout(0.3),
    Dense(1, activation="sigmoid")
])
rnn_model.compile(optimizer="adam", loss="binary_crossentropy", metrics=["accuracy"])

lstm_model = Sequential([
    Embedding(input_dim=10000, output_dim=128),
    LSTM(128, return_sequences=False, dropout=0.2, recurrent_dropout=0.2),
    Dense(64, activation="relu"),
    Dropout(0.3),
    Dense(1, activation="sigmoid")
])
lstm_model.compile(optimizer="adam", loss="binary_crossentropy", metrics=["accuracy"])

# Train the model
history = model.fit(
    X_train, y_train,
    batch_size=32,  # Adjust if needed (try 64 for faster training)
    epochs=20,  # More epochs = better learning (adjust based on validation loss)
    validation_data=(X_test, y_test),
    verbose=1
)

# Train RNN
history_rnn = rnn_model.fit(X_train, y_train, epochs=10, batch_size=32, validation_data=(X_test, y_test), verbose=1)

# Train LSTM
history_lstm = lstm_model.fit(X_train, y_train, epochs=10, batch_size=32, validation_data=(X_test, y_test), verbose=1)

# Train GRU (Already trained, just reference history)
history_gru = history  # Use the history from GRU training

# Evaluate RNN
rnn_loss, rnn_acc = rnn_model.evaluate(X_test, y_test)
print(f"RNN Accuracy: {rnn_acc * 100:.2f}%")

# Evaluate LSTM
lstm_loss, lstm_acc = lstm_model.evaluate(X_test, y_test)
print(f"LSTM Accuracy: {lstm_acc * 100:.2f}%")

# Evaluate GRU
gru_loss, gru_acc = gru_model.evaluate(X_test, y_test)
print(f"GRU Accuracy: {gru_acc * 100:.2f}%")

rnn_model.save("/content/drive/MyDrive/rnn_model.h5")
lstm_model.save("/content/drive/MyDrive/lstm_model.h5")
gru_model.save("/content/drive/MyDrive/gru_model.h5")
print("All models saved successfully!")